package:
  name: roq-cpp-client-template
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CFLAGS=-O3                                                                                                                                                
    - CPPFLAGS=-O3  # [linux]                                                                                                                                   
    - CPPFLAGS=-O3 -D_LIBCPP_DISABLE_AVAILABILITY  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - clang-format
    - cmake
    - make
    - roq-autogen
  host:
    - catch2
    - fmt
    - libabseil
    - roq-api
    - roq-client
    - roq-flags
    - roq-logging
    - roq-market
    - roq-oss-benchmark
    - roq-oss-magic_enum

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C++ Client (a template project)
