package:
  name: roq-cpp-client-template
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - clang-format
    - cmake
    - make
    - roq-autogen
  host:
    - catch2
    - fmt
    - libabseil
    - magic_enum
    - roq-algo
    - roq-api
    - roq-cache
    - roq-client
    - roq-codec
    - roq-flags
    - roq-io
    - roq-logging
    - roq-market
    - benchmark
    - roq-oss-unordered_dense
    - roq-utils

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C++ Client (a template project)
